### ISSUE TITLE
Дашборд

### ISSUE THREAD

**Issue by Nelfimov** [atls/doc-web#17]
## Задача

Создать дашборд [согласно дизайну](https://www.figma.com/file/CuJz4yrhyT9ESzTuAYGRFv/Delta.doc-%E2%80%93-web?type=design&node-id=888-104516&t=VB2wnVsT3yWJAzeA-4).

- [x] Дестопная версия
- [x] Мобильная версия
- [x] Функционал - скрытие/уменьшение
- [x] Перенести дашборд в app и поправить кодстайл

**Comment by TorinAsakura** [comment]
Я бы функционал смены темы вынес бы в отдельный таск, а дэшборд бы делал без него, иначе тут можно надолго встрять
