### ISSUE TITLE
Восстановление пароля

### ISSUE THREAD

**Issue by Nelfimov** [atls/doc-web#22]
### Какого рода задача?

Отображение имени пользователя

### Что и где будем менять?

В дизайне форма проверяет наличие пользователя. Если его нет - [выводит сообщение](https://www.figma.com/file/CuJz4yrhyT9ESzTuAYGRFv/Delta.doc-%E2%80%93-web?type=design&node-id=1018-114642&t=HLPB6DdEY2kC4Otd-4). 
<img width="608" alt="image" src="https://github.com/atls/doc-web/assets/44067768/5c739145-34a6-4c78-82b4-7808c7beb036">

Если есть - отправляет ссылку на восстановление в почту, показывая экран подтверждения [с именем пользователя](https://www.figma.com/file/CuJz4yrhyT9ESzTuAYGRFv/Delta.doc-%E2%80%93-web?type=design&node-id=1018-115186&t=HLPB6DdEY2kC4Otd-4).
<img width="455" alt="image" src="https://github.com/atls/doc-web/assets/44067768/8cdd358a-4c1c-4baa-b0f6-85587d49b57b">

Таким образом можно методом перебора узнать базу пользователей через email, а так же их имена.

Может стоит отключить проверку наличия аккаунта и всегда показывать экран с отправкой письма без указания имени?

### Укажите референс

https://www.ory.sh/docs/kratos/self-service/flows/account-recovery-password-reset#attempted-recovery-notifications

**Comment by vodopmi** [comment]
@Nelfimov согласен 100%, спасибо. исправлю и дам знать

**Comment by vodopmi** [comment]
done. 

- убрал проверку
- изменил текст
