### ISSUE TITLE
Авторизация

### ISSUE THREAD

**Issue by LIMPIX31** [atls/doc-web#4]
## Задача
Реализовать авторизацию в соответствии с дизайном в figma

Фичи:
* [x] - Страница регистрации
* [x] - Страница входа
* [x] - Страница верификации
* [x] - Восстановление пароля

## Материалы
* https://www.figma.com/file/CuJz4yrhyT9ESzTuAYGRFv/Delta.doc-%E2%80%93-web?type=design&node-id=885-119047&t=GF1Iu02ROjHNXkQg-0

## Результат
Возможность входа в аккаунт и регистрации

## Примеры реализаций
* [project-starter](https://github.com/atls/project-starter)

**Comment by Nelfimov** [comment]
## Апдейт

> Регистрация:
> 
> * Редирект происходит так:
>   
>   * Если запрос для Кратоса корректный, то отображается верный компонент (`Complete`), однако в него не тянутся данные из запроса - имя и почта. Через пару секунд происходит редирект в профиль пользователя, после чего опять редирект на логин.
>   * Если запрос некорректный (например имя или фамилия состоит из 1 буквы), то Кратос завершает флоу с статусом 400, однако данные из запроса корректно тянутся в `Complete` - имя и почта.
>     Возможно этот парадокс из-за конфига Кратоса:
> 
> ```
> selfservice:
>   default_browser_return_url: http://localhost:3000/profile/settings
> ```
> 
> Для Кратоса это дефолтный редирект при успешном флоу.
> 
> * [ ]  Пофиксить редирект при регистрации

Предположение не сработало. Конфигурация [согласно документации](https://www.ory.sh/docs/identities/sign-in/actions#show-verification-after-successful-registration) - не дало результата.

По логам видно, что Кратос при успешной регистрации сначала отправляет на индекс, затем на логин (так как не создана сессия).

@TorinAsakura, нужен суппорт.

**Comment by TorinAsakura** [comment]
> ## Апдейт
> > Регистрация:
> > 
> > * Редирект происходит так:
> >   
> >   * Если запрос для Кратоса корректный, то отображается верный компонент (`Complete`), однако в него не тянутся данные из запроса - имя и почта. Через пару секунд происходит редирект в профиль пользователя, после чего опять редирект на логин.
> >   * Если запрос некорректный (например имя или фамилия состоит из 1 буквы), то Кратос завершает флоу с статусом 400, однако данные из запроса корректно тянутся в `Complete` - имя и почта.
> >     Возможно этот парадокс из-за конфига Кратоса:
> > 
> > ```
> > selfservice:
> >   default_browser_return_url: http://localhost:3000/profile/settings
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Для Кратоса это дефолтный редирект при успешном флоу.
> > 
> > * [ ]   Пофиксить редирект при регистрации
> 
> Предположение не сработало. Конфигурация [согласно документации](https://www.ory.sh/docs/identities/sign-in/actions#show-verification-after-successful-registration) - не дало результата.
> 
> По логам видно, что Кратос при успешной регистрации сначала отправляет на индекс, затем на логин (так как не создана сессия).
> 
> @TorinAsakura, нужен суппорт.

пожалуйста, расписывай всегда для таких кейсов шаги для воспроизведения проблемы чтобы я не начинал с субатомного уровня

**Comment by TorinAsakura** [comment]
1. Предлагаю всё-таки начать использовать https…
2. попробуй явно указать домен через session: cookie: domain: localhost
3. Также, рекомендую попробовать, после первых пунктов сделать два разных редирект урла для разных флоу, поставить отладчик и посмотреть как оно будет себя вести

**Comment by TorinAsakura** [comment]
Далее, чот я не понял, почему тут моки, где данные которые я вводил?
![Снимок экрана 2023-06-08 в 01 57 09](https://github.com/atls/doc-web/assets/3940885/522e8a21-9861-4700-853e-727760ecf8da)

Далее, что я вижу в логах, а из логов следует, что есть проблема с токеном верификации: "The verification token is invalid or has already been used. Please retry the flow." Это может произойти, если токен был использован ранее или просрочен.

Ошибки CORS в данном случае не критичны и не должны препятствовать выполнению операций. В конфигурации Kratos проблем не вижу.

**Comment by TorinAsakura** [comment]
Далее, после восстановления и перехода по ссылке из письма - на нужную страницу я был переадресован. Тут надо просто спокойно разобраться с конфигом. Ты не смог найти проблему, потому что искал проблему в кратосе, коде, но не в окружении

![Снимок экрана 2023-06-08 в 02 03 44](https://github.com/atls/doc-web/assets/3940885/48a165db-ea5d-42bc-98b9-79827fbd037f)

**Comment by Nelfimov** [comment]
Реализовано https://github.com/atls/doc-web/pull/7
