### ISSUE TITLE
Регистрация

### ISSUE THREAD

**Issue by eshevlyakova** [atls/doc-web#5]
## Задача

- [x] Сделать страницу ["Регистрация - старт"](https://www.figma.com/file/CuJz4yrhyT9ESzTuAYGRFv/Delta.doc-%E2%80%93-web?type=design&node-id=885-119050&t=8hTXTVJNUTTaBMpb-4)
- [x] Сделать страницу ["Письмо отправлено"](https://www.figma.com/file/CuJz4yrhyT9ESzTuAYGRFv/Delta.doc-%E2%80%93-web?type=design&node-id=888-104259&t=8hTXTVJNUTTaBMpb-4)

**Comment by Nelfimov** [comment]
Реализовано https://github.com/atls/doc-web/pull/7
