### ISSUE TITLE
Страница "Вход"

### ISSUE THREAD

**Issue by eshevlyakova** [atls/doc-web#9]
## Задача

Сделать [страницу "Вход"](https://www.figma.com/file/CuJz4yrhyT9ESzTuAYGRFv/Delta.doc-%E2%80%93-web?type=design&node-id=911-105991&t=I8qQOlY3I9ZKVFjX-4)

**Comment by Nelfimov** [comment]
Реализовано https://github.com/atls/doc-web/pull/7
